Quarks.fetchDirectory; // shift + enter to run this line.  when the process wil be done it will print "-> Quarks"

Quarks.gui; // run this line when above one is done.


// from gui install:
//    Ctk
//    SignalBox
//    XML
//    ExtraWindows
//    atk-sc3
//    FileLog
//    MathLib
//    Hilbert
//    wslib

// right top corner in Quarks GUI click "recompile classs library"
// reopen SuperColider